name: SignCommand
main: iTzFreeHD\Ssigncommand\Main
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
version: 2.0
commands:
  sign:
    description: SignCommand info
    default: op
permissions:
  player.sign:
    default: true
  vip.sign:
    default: op
  admin.sign:
    default: op